### ISSUE TITLE
Feature request: Expand relative paths in dataflow-in path parameters

### ISSUE THREAD

**Issue by ddneilson** [aws-deadline/deadline-cloud#358]
### Use Case

I'm not sure if this should be possible, but it's worth discussing. It may be a bug or a feature request.

I'm trying to craft a Job Bundle that contains files for the Job, and define the job parameters such that the files will be automatically uploaded via Job Attachments and I can access them on the worker via a path mapped job parameter.

To that end, I've tried a Job Bundle with:

`template.yaml`:
```yaml
specificationVersion: jobtemplate-2023-09
name: Job Attachments Test
parameterDefinitions:
- name: BundleDir
  type: PATH
  dataFlow: IN
  objectType: DIRECTORY

steps:
- name: Step
  script:
    actions:
      onRun:
        command: /bin/bash
        args:
        - "{{Param.BundleDir}}/script.sh"
```

`parameter_values.yaml`:
```
parameterValues:
- name: BundleDir
  value: .
```

`script.sh`:
```
#!/bin/bash
echo "Hi!
```

If I run `cd <bundledir>; deadline bundle submit .` then the job submits, and uploads all of the files in the bundle directory as expected. However, the Job is being created with `BundleDir=.` and so the value of `Param.BundleDir` is resolving to ".". 

### Proposed Solution

If a PATH type parameter has dataflow of IN or INOUT and Job Attachments is being used when submitting a Job Bundle via `deadline bundle submit/gui-submit` then perhaps the value of that parameter should be passed as the resolved absolute path rather than its relative value?

This would be a step towards portability with Job Bundles that have files embedded within them.

We may also want to well-define the working-directory for path resolving rather than just always assuming the current working directory. As-is, if we were to adopt this feature request then the Job Bundle becomes fragile since you can only submit it correctly if your current working directory is the bundle directory.
